name: LinterBlack&Flake8

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        flake8 | lintly --log --context=flake8 --commit-sha=${{ github.event.pull_request.head.sha }} --use-checks
    - name: Lint with Black
      run: |
         black . --check 2>&1 >/dev/null | lintly --format=black --use-checks
    - name: Lint with pylint
      run: |
         pylint . --output-format=json | lintly --format=pylint-json --use-checks
      env:
        LINTLY_API_KEY: ${{ secrets.GH_TOKEN }}
