# on: [pull_request]

# jobs:
#   lint:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1
#       - uses: grantmcconnaughey/lintly-flake8-github-action@v1.0
#         with:
#           # The GitHub API token to create reviews with
#           token: ${{ secrets.GH_TOKEN }}
#           # Fail if "new" violations detected or "any", default "new"
#           failIf: new
#           # Additional arguments to pass to flake8, default "." (current directory)
#           args: "--ignore=E121,E123 ."

name: Lint using Flake8

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        pip install -e .
        pip install -r requirements.txt
    - uses: grantmcconnaughey/lintly-flake8-github-action@v1.0
    - name: Lint with flake8
      run: |
        flake8 | lintly --log --context=flake8 --commit-sha=${{ github.event.pull_request.head.sha }} --use-checks
      env:
        LINTLY_API_KEY: ${{ secrets.GH_TOKEN }}
